name: Morning Brief (Kakao)

on:
  schedule:
    # GitHub Actions는 UTC 기준 → 22:30 UTC = 한국 07:30
    - cron: "30 22 * * *"
  workflow_dispatch: {}   # 수동 실행도 가능하게

jobs:
  run-brief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build token.json from secrets
        env:
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: |
          python - << 'PY'
          import os, json, requests
          REST = os.environ["KAKAO_REST_API_KEY"]
          SECRET = os.environ.get("KAKAO_CLIENT_SECRET","")
          REFRESH = os.environ["KAKAO_REFRESH_TOKEN"]
          data = {
            "grant_type":"refresh_token",
            "client_id": REST,
            "refresh_token": REFRESH
          }
          if SECRET:
            data["client_secret"] = SECRET
          r = requests.post("https://kauth.kakao.com/oauth/token", data=data, timeout=15)
          r.raise_for_status()
          resp = r.json()
          access = resp.get("access_token")
          new_refresh = resp.get("refresh_token", REFRESH)
          tok = {"access_token": access, "refresh_token": new_refresh}
          with open("token.json","w",encoding="utf-8") as f:
            json.dump(tok, f, ensure_ascii=False, indent=2)
          PY

    - name: Run morning brief
  run: python send_brief_ci.py

